import { Providers } from "@/lib/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CHEF'S CIRCLE",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
